name: Build Java Project

on:
  push:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cashe: maven
    - run: mvn compile
    - run: mvn package
    - uses: actions/upload-artifact@v4.6.2
      with:
        name: Wochenbericht-windows.jar
        path: ./target/WochenBericht-1.0-SNAPSHOT.jar
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cashe: maven
    - run: mvn compile
    - run: mvn package
    - uses: actions/upload-artifact@v4.6.2
      with:
        name: Wochenbericht-linux.jar
        path: ./target/WochenBericht-1.0-SNAPSHOT.jar